/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogodavelhaimpossivel;

import javax.swing.ImageIcon;

/**
 *
 * @author novoscaminhos
 */
public class jogo extends javax.swing.JFrame {

    /**
     * Creates new form jogo
     */
    public jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        um = new javax.swing.JLabel();
        linhav1 = new javax.swing.JLabel();
        dois = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cinco = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tres = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        seis = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sete = new javax.swing.JLabel();
        quatro = new javax.swing.JLabel();
        oito = new javax.swing.JLabel();
        nove = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        um.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                umMouseClicked(evt);
            }
        });

        linhav1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linhas.jpg"))); // NOI18N
        linhav1.setText("jLabel1");

        dois.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doisMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linhas.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linhas.jpg"))); // NOI18N

        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cincoMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linhas.jpg"))); // NOI18N

        tres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tresMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linhas.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linhas.jpg"))); // NOI18N
        jLabel6.setText("jLabel5");

        seis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seisMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linhas.jpg"))); // NOI18N
        jLabel7.setText("jLabel5");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linhas.jpg"))); // NOI18N
        jLabel8.setText("jLabel5");

        sete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seteMouseClicked(evt);
            }
        });

        quatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quatroMouseClicked(evt);
            }
        });

        oito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oitoMouseClicked(evt);
            }
        });

        nove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(um, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quatro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(linhav1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dois, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oito, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(um, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(linhav1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(nove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(dois, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oito, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int a = 0, b = 0, c = 0, d = 0, e = 0, f = 0, g = 0, h = 0, i = 0;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/linhas.jpg")));
        
    }//GEN-LAST:event_formWindowOpened

    private void umMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_umMouseClicked
        if (b == 0) {
            b++;
            um.setIcon(new ImageIcon(getClass().getResource("/img/xis.png")));
            verf();
        }
        
    }//GEN-LAST:event_umMouseClicked

    private void doisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doisMouseClicked
        if (c == 0) {
            c++;
            dois.setIcon(new ImageIcon(getClass().getResource("/img/xis.png")));
            verf();
        }
        
    }//GEN-LAST:event_doisMouseClicked

    private void tresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresMouseClicked
        if (d == 0) {
            d++;
            tres.setIcon(new ImageIcon(getClass().getResource("/img/xis.png")));
            verf();
        }
        
    }//GEN-LAST:event_tresMouseClicked

    private void quatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quatroMouseClicked
        if (a == 0) {
            a++;
            quatro.setIcon(new ImageIcon(getClass().getResource("/img/xis.png")));
            verf();
        }
        
    }//GEN-LAST:event_quatroMouseClicked

    private void cincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMouseClicked
        if (e == 0) {
            e++;
            cinco.setIcon(new ImageIcon(getClass().getResource("/img/xis.png")));
            verf();
        }
        
    }//GEN-LAST:event_cincoMouseClicked

    private void seisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seisMouseClicked
        if (f == 0) {
            f++;
            seis.setIcon(new ImageIcon(getClass().getResource("/img/xis.png")));
            verf();
        }
        
    }//GEN-LAST:event_seisMouseClicked

    private void seteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seteMouseClicked
        if (g == 0) {
            g++;
            sete.setIcon(new ImageIcon(getClass().getResource("/img/xis.png")));
            verf();
        }
        
    }//GEN-LAST:event_seteMouseClicked

    private void oitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oitoMouseClicked
        if (h == 0) {
            h++;
            oito.setIcon(new ImageIcon(getClass().getResource("/img/xis.png")));
            verf();
        }
    }//GEN-LAST:event_oitoMouseClicked

    private void noveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noveMouseClicked
        if (i == 0) {
            i++;
            nove.setIcon(new ImageIcon(getClass().getResource("/img/xis.png")));
            verf();
        }
        
    }//GEN-LAST:event_noveMouseClicked
    private void verf() {
        int x = 0;
        
        if ((e == 0) && (x == 0)) {
            cinco.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            e+=2;
            x++;
        }else if ((((b == 2) && (a == 2)) || ((i == 2) && (h == 2)) || (e == 2) && (d == 2)) && (x == 0) && (g == 0)) {
            sete.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            g+=2;
            x++;
        } else if ((((i == 2) && (g == 2)) || ((e == 2) && (c == 2))) && (x == 0) && (h == 0)) {
            oito.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            h+=2;
            x++;
        } else if ((((e == 2) && (b == 2)) || ((h == 2) && (g == 2)) || ((d == 2) && (f == 2))) && (x == 0) && (i == 0)) {
            nove.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            i+=2;
            x++;
        } else if ((((b == 2) && (g == 2)) || ((e == 2) && (f == 2))) && (x == 0) && (a == 0)) {
            quatro.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            a+=2;
            x++;
        } else if ((((a == 2) && (e == 2)) || ((d == 2) && (i == 2))) && (x == 0) && (f == 0)) {
            seis.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            f +=2;
            x++;
        } else if ((((a == 2) && (g == 2)) || ((c == 2) && (d == 2)) || ((e == 2) && (i == 2))) && (b == 0) && (b == 0)) {
            um.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            b += 2;
            x++;
        } else if ((((b == 2) && (d == 2) || ((e == 2) && (h == 2))) && (x == 0) && (c == 0))) {
            dois.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            c+=2;
            x++;
        } else if ((((b == 2) && (c == 2)) || ((e == 2) && (g == 2)) || ((f == 2) && (i == 2))) && (x == 0) && (d == 0)) {
            tres.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            d+=2;
            x++;
        } 
        
        
        
        else if ((((b == 1) && (a == 1)) || ((i == 1) && (h == 1)) || (e == 1) && (d == 1)) && (x == 0) && (g == 0)) {
            sete.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            g+=2;
            x++;
        } else if ((((i == 1) && (g == 1)) || ((e == 1) && (c == 1))) && (x == 0) && (h == 0)) {
            oito.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            h+=2;
            x++;
        } else if ((((e == 1) && (b == 1)) || ((h == 1) && (g == 1)) || ((d == 1) && (f == 1))) && (x == 0) && (i == 0)) {
            nove.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            i+=2;
            x++;
        } else if ((((b == 1) && (g == 1)) || ((e == 1) && (f == 1))) && (x == 0) && (a == 0)) {
            quatro.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            a+=2;
            x++;
        } else if ((((a == 1) && (e == 1)) || ((d == 1) && (i == 1))) && (x == 0) && (f == 0)) {
            seis.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            f +=2;
            x++;
        } else if ((((a == 1) && (g == 1)) || ((c == 1) && (d == 1)) || ((e == 1) && (i == 1))) && (b == 0) && (b == 0)) {
            um.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            b += 2;
            x++;
        } else if ((((b == 1) && (d == 1) || ((e == 1) && (h == 1))) && (x == 0) && (c == 0))) {
            dois.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            c+=2;
            x++;
        } else if ((((b == 1) && (c == 1)) || ((e == 1) && (g == 1)) || ((f == 1) && (i == 1))) && (x == 0) && (d == 0)) {
            tres.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            d+=2;
            x++;
        }
        
        //armadilhas:
        
        if ((e == 1) && (x == 0) && (g == 0)) {
            sete.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            g+=2;
            x++;
        } else if ((e == 1) && (d == 1) && (g == 2)) {
            um.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            b+=2;
            x++;
        }
        
        if ((((b == 1) && (i == 1)) || ((g == 1) && (d == 1))) && (x == 0) && (a == 0)) {
            quatro.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            a+=2;
            x++;
        }
        
        if ((((h == 1) && (f == 1)) && (x == 0) && (i == 0))) {
            nove.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            i += 2;
            x++;
        } else if ((((a == 1) && (h == 1) && (x == 0) && (g == 0)))) {
            sete.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            g+=2;
            x++;
        } else if ((((a == 1) && (c == 1) && (x == 0) && (b == 0)))) {
            um.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            b+=2;
            x++;
        } else if ((c == 1) && (f == 1) && (x == 0) && (d == 0)) {
            tres.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            d+=2;
            x++;
        }
        
        if (((((b == 1) || (d == 1)) && (h == 1)) || (((d == 1) || (i == 1)) && (a == 1))) && (x == 0) && (g == 0)) {
            sete.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            g+=2;
            x++;
        } else if (((((g == 1) || (i == 1)) && (c == 1)) || (((b == 1) || (g == 1)) && (f == 1))) && (x == 0) && (d == 0)) {
            tres.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            d+=2;
            x++;
        }
        int cc = 1, jog = 0;
        if (x == 0) {
        while (jog != cc) {
            cc = (int)Math.round(1 + Math.random() * 8);
            switch (cc) {
                case 1:
                    if (b == 0)
                        jog = cc;
                    break;
                case 2:
                    if (c == 0)
                        jog = cc;
                    break;
                case 3:
                    if (d == 0)
                        jog = cc;
                    break;
                case 4:
                    if (a == 0) {
                        jog = cc;
                    }
                    break;
                case 5:
                    if (e == 0)
                        jog = cc;
                    break;
                case 6:
                    if (f == 0)
                        jog = cc;
                    break;
                case 7:
                    if (g == 0)
                        jog = cc;
                    break;
                case 8:
                    if (h == 0)
                        jog = cc;
                    break;
                case 9:
                    if (i == 0)
                        jog = cc;
                    break;                   
            }
        }
        switch (jog) {
            case 1:
            um.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
            b+=2;
            x++;
            break;
            case 2:
                dois.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
                c+=2;
                x++;
                break;
            case 3:
                tres.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
                d+=2;
                x++;
                break;
            case 4:
                quatro.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
                a+=2;
                x++;
                break;
            case 5:
                cinco.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
                e+=2;
                x++;
                break;
            case 6:
                seis.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
                f+=2;
                x++;
                break;
            case 7:
                sete.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
                g+=2;
                x++;
                break;
            case 8:
                oito.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
                h+=2;
                x++;
                break;
            case 9:
                nove.setIcon(new ImageIcon(getClass().getResource("/img/ball.png")));
                i+=2;
                x++;
                break;
        }
        }
        
            
        
        
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cinco;
    private javax.swing.JLabel dois;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel linhav1;
    private javax.swing.JLabel nove;
    private javax.swing.JLabel oito;
    private javax.swing.JLabel quatro;
    private javax.swing.JLabel seis;
    private javax.swing.JLabel sete;
    private javax.swing.JLabel tres;
    private javax.swing.JLabel um;
    // End of variables declaration//GEN-END:variables
}
